# docker-compose.yml

version: '3.8'

services:
  backend:
    container_name: cassia-api-backend-main
    image: cassia-api-backend-main
    build: .
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/code
    ports:
      - 8000:8000
    expose:
      - 8000

# If running behind a proxy like Nginx or Traefik add --proxy-headers
# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--proxy-headers"]
